cluster:
  name: elastic-local
discovery:
  zen:
    minimum_master_nodes: 1
    ping:
      unicast:
        hosts: [ 'elasticsearch' ]
path:
  logs: /var/log/elasticsearch
network:
  host: ['0.0.0.0']
node:
  name: elastic-local
  data: true
  master: true
