cluster:
  name: elastic-local
discovery:
  zen:
    minimum_master_nodes: 1
    ping:
      unicast:
        hosts: [ 'elasticsearch-1', 'elasticsearch-2' ]
path:
  logs: /var/log/elasticsearch
  data: /var/data
  repo: /repo/
network:
  host: ['0.0.0.0']
node:
  name: ${HOSTNAME}
  data: true
  master: true
