filebeat.prospectors:

- input_type: log
  paths:
    - /var/log/*.log
  document_type: systemlog
- input_type: log
  paths:
    - /*.log
  document_type: applog

name: "filebeat-docker"
tags: ["test-service", "filter-dev"]
fields_under_root: true
fields:
  environment: staging

output.redis:
  hosts: ["redis"]
  key: "filebeat"
  db: 0
  timeout: 5
