logging.level: info 
logging.to_files: true
logging.to_syslog: false
logging.files:
  path: /tmp/
  name: filebeat.log
  keepfiles: 7
  permissions: 0644



filebeat.prospectors:
- type: log #redis|stdin|stdout|udp
  paths:
  - /tmp/logs/*.log
  fields_under_root: true
  fields:
    topic: log
- type: log
  paths:
    - /tmp/multiline.log
  fields:
    topic: multilinelog
  multiline:
    pattern: '^\d'
    negate:  true
    match:   after

output.kafka:
  hosts: ["kafka-1:9092"]
  topic: "filebeat-%{[topic]}"
  partition.round_robin:
    reachable_only: true

  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000
